spring:
  application:
    name: userServer

  datasource:
    url: jdbc:postgresql://localhost:5444/userDB
    username: honey
    password: honey123

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8092/realms/fitness-app

server:
  port: 8082



