spring:
  application:
    name: dietService

  datasource:
    url: jdbc:postgresql://localhost:5444/diet
    username: honey
    password: honey123

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8092/realms/fitness-app

  jackson:
    time-zone: Asia/Kolkata

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8088

gemini:
  api:
    key: ${gemini_api_key}


