server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userService
              uri: http://localhost:8082
              predicates:
                - Path=/api/users/**
            - id: activityService
              uri: http://localhost:8087
              predicates:
                - Path=/api/activities/**
            - id: dietService
              uri: http://localhost:8088
              predicates:
                - Path=/api/diet/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8092/realms/fitness-app/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,env,metrics
  endpoint:
    gateway:
      access: unrestricted
